### ISSUE TITLE
Add a README file

### ISSUE THREAD

**Issue by kallen84** [kallen84/TreehouseDemo#1]
Create README.md file to give an overview of what this repo is for.

**Comment by kallen84** [comment]
## TODO

_Learn Git and GitHub_
 Learn Git command
- [ ] Learn GitHub Interface 🚀 
- [ ] Learn To connect Git to Github 🚀 
- [ ] Become a Git/GitHub Origin Master! 🎸 

👍 👍 👍
